import = ["/home/rsuijker/.config/alacritty/catppuccin/catppuccin-frappe.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
opacity = 0.7
