format = """
[░▒▓](sky)\
$os\
$username\
[](fg:sky bg:blue)\
$directory\
[](fg:blue bg:surface1)\
$git_branch\
$git_status\
[](fg:surface1 bg:base)\
$cmd_duration\
[](fg:base bg:base)\
$time\
[ ](fg:base)\
\n$character"""

palette = 'mocha'

[cmd_duration]
min_time = 2000
format = '[  ](fg:maroon bg:base)[$duration](bold fg:rosewater bg:base)'

[username]
show_always = true
style_user = "bg:sky fg:crust"
style_root = "bg:red fg:base"
format = '[$user ]($style)'
disabled = false

[os]
format = '[$symbol]($style)'
style = "fg:mantle bg:sky"
disabled = false

[os.symbols]
Arch = " "
Macos = " "
Manjaro = " "

[directory]
style = "fg:surface2 bg:blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"devel" = " "

[git_branch]
symbol = ""
style = "bg:surface1"
format = '[[ $symbol $branch ](fg:mauve bg:surface1)]($style)'

[git_status]
style = "bg:surface1"
format = '[[($all_status$ahead_behind )](fg:lavender bg:surface1)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:base"
format = '[[  $time ](fg:text bg:base)]($style)'

[palettes.mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
